force-app/main/default/objects/cgcloud__Account_Template__c/cgcloud__Account_Template__c.object-meta.xml
<CustomObject>
    <description>holds the details of the account template object to be used for accounts.</description>
    <label>Customer Template</label>
    <nameField>
        <label>Customer Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Account_Template__c/fields/cgcloud__Active__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Specifies if Customer Template record is active.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Template__c/fields/cgcloud__Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Sales_Org__c</fullName>
    <description>Describes the sales organization which the customer template belongs to.</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/cgcloud__Job_Definition_List__c.object-meta.xml
<CustomObject>
    <description>Holds the set of questions/surveys that are to be carried out in the respective call and contains further relevant configurations.</description>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/fields/cgcloud__Description_Language_1__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Description_Language_1__c</fullName>
    <label>Description Language 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/fields/cgcloud__Job_Definition_List_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_List_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Activity Template</label>
    <referenceTo>cgcloud__Job_Definition_List_Template__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Job_Definition_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/fields/cgcloud__Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Sales_Org__c</fullName>
    <description>Describes sales organization which the activity belongs to.</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/fields/cgcloud__Visit_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Visit_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Visit Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cgcloud__Visit_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>cgcloud__Visit_Template__c.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>$Source.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Visit_Template__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Job_Definition_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List_Template__c/cgcloud__Job_Definition_List_Template__c.object-meta.xml
<CustomObject>
    <description>Template that controls the behavior of job definition lists.</description>
    <label>Activity Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_Definition_List_Template__c/fields/cgcloud__Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/cgcloud__Job_Definition_Template__c.object-meta.xml
<CustomObject>
    <description>Holds the definition of questions / product surveys that are available in the system.</description>
    <label>Job Definition Template</label>
    <nameField>
        <label>Job Definition Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Definition Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/fields/cgcloud__Active__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/fields/cgcloud__Data_Type__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Data_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Data Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>cgcloud__Data_Type__c.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Data_Type__c</referenceTo>
    <relationshipLabel>Job Definition Templates</relationshipLabel>
    <relationshipName>Job_Definition_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/fields/cgcloud__Job_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Template</label>
    <referenceTo>cgcloud__Job_Template__c</referenceTo>
    <relationshipLabel>Job Definition Templates</relationshipLabel>
    <relationshipName>Job_Definition_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/cgcloud__Job_DL_Job_Definition_Template__c.object-meta.xml
<CustomObject>
    <description>Holds the specific questions/surveys used in the job definition list.</description>
    <label>Question</label>
    <nameField>
        <displayFormat>JDL-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Job_Action_Success__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Action_Success__c</fullName>
    <label>Job Action Success</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cgcloud__Mandatory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Detach</fullName>
            </value>
            <value>
                <fullName>Validation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Job_Definition_List__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_List__c</fullName>
    <label>Activity</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Job_Definition_List__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Job_Definition_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Job_Definition_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Definition Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cgcloud__Job_Definition_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>cgcloud__Job_Definition_Template__c.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>$Source.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Job_Definition_Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Job_Definition_Links</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Job_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Template__c</fullName>
    <formula>cgcloud__Job_Definition_Template__r.cgcloud__Job_Template__r.Name</formula>
    <label>Job Template</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Mandatory__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Sales_Org__c</fullName>
    <description>Describes sales organization which the job definition template assignment of the activity (and the activity itself) belongs to.</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Template__c/cgcloud__Visit_Template__c.object-meta.xml
<CustomObject>
    <description>Template describing basic call behaviour.</description>
    <label>Visit Template</label>
    <nameField>
        <label>Visit Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit/fields/cgcloud__Visit_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Visit_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Visit Template associated to the Call</description>
    <label>Visit Template</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No matches found or visit Template is not active.</errorMessage>
        <filterItems>
            <field>cgcloud__Visit_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Visit_Template__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

Visit_Activity_Agent_Backup/Visit_Activity_Agent_Backup/force-app/main/default/classes/GetVisitActivitiesTest.cls
@isTest
public class GetVisitActivitiesTest {

    @isTest
    static void testGetVisitActivities() {
        // Create test Account Template
        cgcloud__Account_Template__c at = new cgcloud__Account_Template__c(
            Name = 'Test Account Template',
            cgcloud__Sales_Org__c = '0001'
        );
        insert at;

        // Create test Account
        Account acc = new Account(
            Name = 'Test Account',
            cgcloud__Account_Template__c = at.Id
        );
        insert acc;

        // Create test Retail Store
        RetailStore store = new RetailStore(
            Name = 'Test Store',
            AccountId = acc.Id
        );
        insert store;

        // Create test Visit Template
        cgcloud__Visit_Template__c vt = new cgcloud__Visit_Template__c(
            Name = 'Test Visit Template',
            cgcloud__Sales_Org__c = '0001'
        );
        insert vt;

        // Create test Visit
        Visit v = new Visit(
            AccountId = acc.Id,
            PlaceId = store.Id,
            cgcloud__Visit_Template__c = vt.Id,
            PlannedVisitStartTime = Datetime.now(),
            Status = 'Planned'
        );
        insert v;

        // Create test Job Definition List Template
        cgcloud__Job_Definition_List_Template__c jdlt = new cgcloud__Job_Definition_List_Template__c(
            Name = 'Test JDL Template',
            cgcloud__Sales_Org__c = '0001'
        );
        insert jdlt;

        // Create test Job Definition List
        cgcloud__Job_Definition_List__c jdl = new cgcloud__Job_Definition_List__c(
            Name = 'Test JDL',
            cgcloud__Visit_Template__c = vt.Id,
            cgcloud__Job_Definition_List_Template__c = jdlt.Id,
            cgcloud__Active__c = true,
            cgcloud__Sales_Org__c = '0001'
        );
        insert jdl;

        // Create Data Type
        cgcloud__Data_Type__c dt = new cgcloud__Data_Type__c(
            Name = 'Toggle',
            cgcloud__Sales_Org__c = '0001'
        );
        insert dt;

        // Create Job Template
        cgcloud__Job_Template__c jt = new cgcloud__Job_Template__c(
            Name = 'Test Job Template',
            cgcloud__Sales_Org__c = '0001'
        );
        insert jt;

        // Create Job Definition Template
        cgcloud__Job_Definition_Template__c jdt = new cgcloud__Job_Definition_Template__c(
            Name = 'Test JDT Question',
            cgcloud__Description_Language_1__c = 'Test Description',
            cgcloud__Data_Type__c = dt.Id,
            cgcloud__Job_Template__c = jt.Id,
            cgcloud__Sales_Org__c = '0001'
        );
        insert jdt;

        // Create Link (JDL to JDT)
        cgcloud__Job_DL_Job_Definition_Template__c link = new cgcloud__Job_DL_Job_Definition_Template__c(
            cgcloud__Job_Definition_List__c = jdl.Id,
            cgcloud__Job_Definition_Template__c = jdt.Id,
            cgcloud__Mandatory__c = true,
            cgcloud__Job_Action_Success__c = 'Validation',
            cgcloud__Sales_Org__c = '0001'
        );
        insert link;

        // Execute Invocable
        GetVisitActivities.Request req = new GetVisitActivities.Request();
        req.visitId = v.Id;

        Test.startTest();
        List<GetVisitActivities.Result> results = GetVisitActivities.execute(new List<GetVisitActivities.Request>{req});
        Test.stopTest();

        System.assertEquals(1, results.size());
        System.assertEquals(1, results[0].activities.size());
        System.assertEquals('Test JDL', results[0].activities[0].activityName);
        System.assertEquals(1, results[0].activities[0].questions.size());
        System.assertEquals('Test JDT Question', results[0].activities[0].questions[0].questionName);
    }
}