force-app/main/default/objects/cgcloud__Account_Template__c/cgcloud__Account_Template__c.object-meta.xml
<CustomObject>
    <description>holds the details of the account template object to be used for accounts.</description>
    <label>Customer Template</label>
    <nameField>
        <label>Customer Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Account_Template__c/fields/cgcloud__Active__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Specifies if Customer Template record is active.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cgcloud__Account_Template__c/fields/cgcloud__Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Sales_Org__c</fullName>
    <description>Describes the sales organization which the customer template belongs to.</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/cgcloud__Job_Definition_List__c.object-meta.xml
<CustomObject>
    <description>Holds the set of questions/surveys that are to be carried out in the respective call and contains further relevant configurations.</description>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/fields/cgcloud__Description_Language_1__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Description_Language_1__c</fullName>
    <label>Description Language 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/fields/cgcloud__Job_Definition_List_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_List_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Activity Template</label>
    <referenceTo>cgcloud__Job_Definition_List_Template__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Job_Definition_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/fields/cgcloud__Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Sales_Org__c</fullName>
    <description>Describes sales organization which the activity belongs to.</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/fields/cgcloud__Visit_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Visit_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Visit Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cgcloud__Visit_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>cgcloud__Visit_Template__c.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>$Source.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Visit_Template__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Job_Definition_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List_Template__c/cgcloud__Job_Definition_List_Template__c.object-meta.xml
<CustomObject>
    <description>Template that controls the behavior of job definition lists.</description>
    <label>Activity Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_Definition_List_Template__c/fields/cgcloud__Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/cgcloud__Job_Definition_Template__c.object-meta.xml
<CustomObject>
    <description>Holds the definition of questions / product surveys that are available in the system.</description>
    <label>Job Definition Template</label>
    <nameField>
        <label>Job Definition Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Definition Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/fields/cgcloud__Active__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/fields/cgcloud__Data_Type__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Data_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Data Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>cgcloud__Data_Type__c.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Data_Type__c</referenceTo>
    <relationshipLabel>Job Definition Templates</relationshipLabel>
    <relationshipName>Job_Definition_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/fields/cgcloud__Job_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Template</label>
    <referenceTo>cgcloud__Job_Template__c</referenceTo>
    <relationshipLabel>Job Definition Templates</relationshipLabel>
    <relationshipName>Job_Definition_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/cgcloud__Job_DL_Job_Definition_Template__c.object-meta.xml
<CustomObject>
    <description>Holds the specific questions/surveys used in the job definition list.</description>
    <label>Question</label>
    <nameField>
        <displayFormat>JDL-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Job_Definition_List__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_List__c</fullName>
    <label>Activity</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Job_Definition_List__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Job_Definition_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Job_Definition_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Definition Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cgcloud__Job_Definition_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>cgcloud__Job_Definition_Template__c.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>$Source.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Job_Definition_Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Job_Definition_Links</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Job_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Template__c</fullName>
    <formula>cgcloud__Job_Definition_Template__r.cgcloud__Job_Template__r.Name</formula>
    <label>Job Template</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Sales_Org__c</fullName>
    <description>Describes sales organization which the job definition template assignment of the activity (and the activity itself) belongs to.</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>cgcloud__Sales_Org</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Job__c/cgcloud__Visit_Job__c.object-meta.xml
<CustomObject>
    <description>Contains answered questions and product surveys (jobs).</description>
    <label>Visit Job</label>
    <nameField>
        <displayFormat>CJ-{0000}</displayFormat>
        <label>Visit Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Visit_Job__c/fields/cgcloud__Done__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Job__c/fields/cgcloud__Job_Definition_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Definition Template</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2) OR (3 AND 4))</booleanFilter>
        <filterItems>
            <field>$Source.cgcloud__Product__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>cgcloud__Job_Definition_Template__c.cgcloud__Job_Template__r.cgcloud__Product_Reference__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.cgcloud__Product__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>cgcloud__Job_Definition_Template__c.cgcloud__Job_Template__r.cgcloud__Product_Reference__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Job_Definition_Template__c</referenceTo>
    <relationshipLabel>Visit Jobs</relationshipLabel>
    <relationshipName>Call_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Job__c/fields/cgcloud__Value__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Job__c/fields/cgcloud__Visit__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Visit__c</fullName>
    <label>Visit</label>
    <referenceTo>Visit</referenceTo>
    <relationshipLabel>Visit Jobs</relationshipLabel>
    <relationshipName>Call_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Template__c/cgcloud__Visit_Template__c.object-meta.xml
<CustomObject>
    <description>Template describing basic call behaviour.</description>
    <label>Visit Template</label>
    <nameField>
        <label>Visit Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit/fields/cgcloud__Visit_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Visit_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Visit Template associated to the Call</description>
    <label>Visit Template</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No matches found or visit Template is not active.</errorMessage>
        <filterItems>
            <field>cgcloud__Visit_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Visit_Template__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

Visit_Activity_Agent_Backup/Visit_Activity_Agent_Backup/force-app/main/default/classes/GetVisitJobsStatusTest.cls
@isTest
public class GetVisitJobsStatusTest {

    @isTest
    static void testGetVisitJobsStatus() {
        // Create test Account Template
        cgcloud__Account_Template__c at = new cgcloud__Account_Template__c(
            Name = 'Test Account Template',
            cgcloud__Sales_Org__c = '0001'
        );
        insert at;

        // Create test Account
        Account acc = new Account(
            Name = 'Test Account',
            cgcloud__Account_Template__c = at.Id
        );
        insert acc;

        // Create test Retail Store
        RetailStore store = new RetailStore(
            Name = 'Test Store',
            AccountId = acc.Id
        );
        insert store;

        // Create test Visit Template
        cgcloud__Visit_Template__c vt = new cgcloud__Visit_Template__c(
            Name = 'Test Visit Template',
            cgcloud__Sales_Org__c = '0001'
        );
        insert vt;

        // Create test Visit
        Visit v = new Visit(
            AccountId = acc.Id,
            PlaceId = store.Id,
            cgcloud__Visit_Template__c = vt.Id,
            PlannedVisitStartTime = Datetime.now(),
            Status = 'Planned'
        );
        insert v;

        // Create test Job Definition List Template
        cgcloud__Job_Definition_List_Template__c jdlt = new cgcloud__Job_Definition_List_Template__c(
            Name = 'Test JDL Template',
            cgcloud__Sales_Org__c = '0001'
        );
        insert jdlt;

        // Create JDL and JDT to simulate planned templates
        cgcloud__Job_Definition_List__c jdl = new cgcloud__Job_Definition_List__c(
            Name = 'Test JDL',
            cgcloud__Visit_Template__c = vt.Id,
            cgcloud__Job_Definition_List_Template__c = jdlt.Id,
            cgcloud__Active__c = true,
            cgcloud__Sales_Org__c = '0001'
        );
        insert jdl;

        // Create Data Type
        cgcloud__Data_Type__c dt = new cgcloud__Data_Type__c(
            Name = 'Toggle',
            cgcloud__Sales_Org__c = '0001'
        );
        insert dt;

        // Create Job Template
        cgcloud__Job_Template__c jt = new cgcloud__Job_Template__c(
            Name = 'Test Job Template',
            cgcloud__Sales_Org__c = '0001'
        );
        insert jt;

        cgcloud__Job_Definition_Template__c jdtPlannedOnly = new cgcloud__Job_Definition_Template__c(
            Name = 'Planned Only Question',
            cgcloud__Description_Language_1__c = 'Planned Only Desc',
            cgcloud__Data_Type__c = dt.Id,
            cgcloud__Job_Template__c = jt.Id,
            cgcloud__Sales_Org__c = '0001'
        );
        insert jdtPlannedOnly;

        cgcloud__Job_DL_Job_Definition_Template__c linkPlannedOnly = new cgcloud__Job_DL_Job_Definition_Template__c(
            cgcloud__Job_Definition_List__c = jdl.Id,
            cgcloud__Job_Definition_Template__c = jdtPlannedOnly.Id,
            cgcloud__Sales_Org__c = '0001'
        );
        insert linkPlannedOnly;

        cgcloud__Job_Definition_Template__c jdtAnswered = new cgcloud__Job_Definition_Template__c(
            Name = 'Answered Question',
            cgcloud__Description_Language_1__c = 'Answered Desc',
            cgcloud__Data_Type__c = dt.Id,
            cgcloud__Job_Template__c = jt.Id,
            cgcloud__Sales_Org__c = '0001'
        );
        insert jdtAnswered;

        cgcloud__Job_DL_Job_Definition_Template__c linkAnswered = new cgcloud__Job_DL_Job_Definition_Template__c(
            cgcloud__Job_Definition_List__c = jdl.Id,
            cgcloud__Job_Definition_Template__c = jdtAnswered.Id,
            cgcloud__Sales_Org__c = '0001'
        );
        insert linkAnswered;

        // Create an answered Visit Job
        cgcloud__Visit_Job__c vjAnswered = new cgcloud__Visit_Job__c(
            cgcloud__Visit__c = v.Id,
            cgcloud__Job_Definition_Template__c = jdtAnswered.Id,
            cgcloud__Done__c = true,
            cgcloud__Value__c = 'Yes'
        );
        insert vjAnswered;

        // Create an unanswered/pending actual Visit Job
        cgcloud__Job_Definition_Template__c jdtPendingActual = new cgcloud__Job_Definition_Template__c(
            Name = 'Pending Actual Question',
            cgcloud__Description_Language_1__c = 'Pending Actual Desc',
            cgcloud__Data_Type__c = dt.Id,
            cgcloud__Job_Template__c = jt.Id,
            cgcloud__Sales_Org__c = '0001'
        );
        insert jdtPendingActual;

        cgcloud__Job_DL_Job_Definition_Template__c linkPendingActual = new cgcloud__Job_DL_Job_Definition_Template__c(
            cgcloud__Job_Definition_List__c = jdl.Id,
            cgcloud__Job_Definition_Template__c = jdtPendingActual.Id,
            cgcloud__Sales_Org__c = '0001'
        );
        insert linkPendingActual;

        cgcloud__Visit_Job__c vjPending = new cgcloud__Visit_Job__c(
            cgcloud__Visit__c = v.Id,
            cgcloud__Job_Definition_Template__c = jdtPendingActual.Id,
            cgcloud__Done__c = false,
            cgcloud__Value__c = ''
        );
        insert vjPending;

        // Test with Status Filter: answered
        GetVisitJobsStatus.Request reqAnswered = new GetVisitJobsStatus.Request();
        reqAnswered.visitId = v.Id;
        reqAnswered.statusFilter = 'answered';

        // Test with Status Filter: pending
        GetVisitJobsStatus.Request reqPending = new GetVisitJobsStatus.Request();
        reqPending.visitId = v.Id;
        reqPending.statusFilter = 'pending';

        // Test with Status Filter: all
        GetVisitJobsStatus.Request reqAll = new GetVisitJobsStatus.Request();
        reqAll.visitId = v.Id;
        reqAll.statusFilter = 'all';

        Test.startTest();
        List<GetVisitJobsStatus.Result> resAnsweredList = GetVisitJobsStatus.execute(new List<GetVisitJobsStatus.Request>{reqAnswered});
        List<GetVisitJobsStatus.Result> resPendingList = GetVisitJobsStatus.execute(new List<GetVisitJobsStatus.Request>{reqPending});
        List<GetVisitJobsStatus.Result> resAllList = GetVisitJobsStatus.execute(new List<GetVisitJobsStatus.Request>{reqAll});
        Test.stopTest();

        // Verify Answered
        System.assertEquals(1, resAnsweredList.size());
        System.assertEquals(1, resAnsweredList[0].jobs.size(), 'Should have 1 answered job');
        System.assertEquals('Answered Question', resAnsweredList[0].jobs[0].questionName);
        System.assertEquals(true, resAnsweredList[0].jobs[0].isDone);

        // Verify Pending
        System.assertEquals(1, resPendingList.size());
        // Should have 2 pending jobs: vjPending (pending actual job) and jdtPlannedOnly (planned template with no actual jobs)
        System.assertEquals(2, resPendingList[0].jobs.size(), 'Should have 2 pending jobs');
        
        Set<String> pendingNames = new Set<String>();
        for (GetVisitJobsStatus.JobStatusInfo info : resPendingList[0].jobs) {
            pendingNames.add(info.questionName);
            System.assertEquals(false, info.isDone);
        }
        System.assert(pendingNames.contains('Pending Actual Question'), 'Should contain Pending Actual Question');
        System.assert(pendingNames.contains('Planned Only Question'), 'Should contain Planned Only Question');

        // Verify All
        System.assertEquals(1, resAllList.size());
        System.assertEquals(3, resAllList[0].jobs.size(), 'Should have 3 total jobs');
    }
}