force-app/main/default/objects/cgcloud__Field_Sales_Activity__c/cgcloud__Field_Sales_Activity__c.object-meta.xml
<CustomObject>
    <description>Holds the details of the field sales activity object. Field Sales Activity (FSA) covers a set of job definition lists.</description>
    <label>Field Sales Activity</label>
    <nameField>
        <displayFormat>FSA-{0000}</displayFormat>
        <label>Field Sales Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Sales Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Field_Sales_Activity__c/fields/cgcloud__Description__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Description__c</fullName>
    <formula>CASE($User.cgcloud__Language_Postfix__c,
&quot;Language1&quot;, cgcloud__Description_Language_1__c,
&quot;Language2&quot;, BLANKVALUE(cgcloud__Description_Language_2__c,cgcloud__Description_Language_1__c),
&quot;Language3&quot;, BLANKVALUE(cgcloud__Description_Language_3__c,cgcloud__Description_Language_1__c),
&quot;Language4&quot;, BLANKVALUE(cgcloud__Description_Language_4__c,cgcloud__Description_Language_1__c),
cgcloud__Description_Language_1__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/cgcloud__Job_Definition_List__c.object-meta.xml
<CustomObject>
    <description>Holds the set of questions/surveys that are to be carried out in the respective call and contains further relevant configurations.</description>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/fields/cgcloud__Field_Sales_Activity__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Field_Sales_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Sales Activity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>cgcloud__Field_Sales_Activity__c.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Field_Sales_Activity__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Job_Definition_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/fields/cgcloud__Visit_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Visit_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Visit Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cgcloud__Visit_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>cgcloud__Visit_Template__c.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>$Source.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Visit_Template__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Job_Definition_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/cgcloud__Job_Definition_Template__c.object-meta.xml
<CustomObject>
    <description>Holds the definition of questions / product surveys that are available in the system.</description>
    <label>Job Definition Template</label>
    <nameField>
        <label>Job Definition Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Definition Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/fields/cgcloud__Active__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/fields/cgcloud__Data_Type__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Data_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Data Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>cgcloud__Data_Type__c.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Data_Type__c</referenceTo>
    <relationshipLabel>Job Definition Templates</relationshipLabel>
    <relationshipName>Job_Definition_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/fields/cgcloud__Description__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Description__c</fullName>
    <formula>CASE($User.cgcloud__Language_Postfix__c,
      &quot;Language1&quot;, cgcloud__Description_Language_1__c,
      &quot;Language2&quot;, BLANKVALUE(cgcloud__Description_Language_2__c,cgcloud__Description_Language_1__c),
      &quot;Language3&quot;, BLANKVALUE(cgcloud__Description_Language_3__c,cgcloud__Description_Language_1__c),
      &quot;Language4&quot;, BLANKVALUE(cgcloud__Description_Language_4__c,cgcloud__Description_Language_1__c),
      cgcloud__Description_Language_1__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/cgcloud__Job_DL_Job_Definition_Template__c.object-meta.xml
<CustomObject>
    <description>Holds the specific questions/surveys used in the job definition list.</description>
    <label>Question</label>
    <nameField>
        <displayFormat>JDL-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Description__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Description__c</fullName>
    <formula>cgcloud__Job_Definition_Template__r.cgcloud__Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Job_Definition_List__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_List__c</fullName>
    <label>Activity</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Job_Definition_List__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Job_Definition_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Job_Definition_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Definition Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cgcloud__Job_Definition_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>cgcloud__Job_Definition_Template__c.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>$Source.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Job_Definition_Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Job_Definition_Links</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Mandatory__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Template__c/cgcloud__Visit_Template__c.object-meta.xml
<CustomObject>
    <description>Template describing basic call behaviour.</description>
    <label>Visit Template</label>
    <nameField>
        <label>Visit Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit/fields/cgcloud__Visit_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Visit_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Visit Template associated to the Call</description>
    <label>Visit Template</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No matches found or visit Template is not active.</errorMessage>
        <filterItems>
            <field>cgcloud__Visit_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Visit_Template__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

Visit_Activity_Agent_Backup/Visit_Activity_Agent_Backup/force-app/main/default/classes/GetVisitActivities.cls
public with sharing class GetVisitActivities {

    public class Request {
        @InvocableVariable(label='Visit ID' description='The ID of the Visit record' required=true)
        public String visitId;
    }

    public class Result {
        @InvocableVariable(label='Activities' description='List of activities and questions/surveys associated with the visit template')
        public List<ActivityInfo> activities;
    }

    public class ActivityInfo {
        @InvocableVariable(label='Activity ID' description='The ID of the Job Definition List record')
        public String activityId;

        @InvocableVariable(label='Activity Name' description='The Name of the activity')
        public String activityName;

        @InvocableVariable(label='Description' description='The description of the activity')
        public String description;

        @InvocableVariable(label='Questions' description='List of related questions/surveys')
        public List<QuestionInfo> questions;
    }

    public class QuestionInfo {
        @InvocableVariable(label='Question ID' description='The ID of the Job Definition Template record')
        public String questionId;

        @InvocableVariable(label='Question Name' description='The Name of the question/survey')
        public String questionName;

        @InvocableVariable(label='Description' description='The description of the question/survey')
        public String description;

        @InvocableVariable(label='Mandatory' description='Is this question mandatory?')
        public Boolean mandatory;
    }

    @InvocableMethod(
        label='Get Visit Activities'
        description='Retrieves activities, questions, and surveys associated with a visit based on its visit template.'
    )
    public static List<Result> execute(List<Request> requests) {
        List<Result> results = new List<Result>();
        
        // Collect visit IDs
        Set<Id> visitIds = new Set<Id>();
        for (Request req : requests) {
            if (String.isNotBlank(req.visitId)) {
                visitIds.add((Id)req.visitId);
            }
        }
        
        if (visitIds.isEmpty()) {
            for (Integer i = 0; i < requests.size(); i++) {
                results.add(new Result());
            }
            return results;
        }

        // Query Visit records to get their templates
        Map<Id, Visit> visitsMap = new Map<Id, Visit>([
            SELECT Id, cgcloud__Visit_Template__c
            FROM Visit
            WHERE Id IN :visitIds
            WITH USER_MODE
        ]);

        // Map visit template IDs to visit IDs
        Map<Id, Set<Id>> templateToVisits = new Map<Id, Set<Id>>();
        for (Visit v : visitsMap.values()) {
            if (v.cgcloud__Visit_Template__c != null) {
                if (!templateToVisits.containsKey(v.cgcloud__Visit_Template__c)) {
                    templateToVisits.put(v.cgcloud__Visit_Template__c, new Set<Id>());
                }
                templateToVisits.get(v.cgcloud__Visit_Template__c).add(v.Id);
            }
        }

        // Query Job Definition Lists for these templates
        Map<Id, List<cgcloud__Job_Definition_List__c>> templateToJDLs = new Map<Id, List<cgcloud__Job_Definition_List__c>>();
        if (!templateToVisits.isEmpty()) {
            Set<Id> templateIds = templateToVisits.keySet();
            List<cgcloud__Job_Definition_List__c> jdls = [
                SELECT Id, Name, cgcloud__Description__c, cgcloud__Visit_Template__c,
                       cgcloud__Field_Sales_Activity__c, cgcloud__Field_Sales_Activity__r.Name, cgcloud__Field_Sales_Activity__r.cgcloud__Description__c,
                       (SELECT Id, Name,
                               cgcloud__Job_Definition_Template__c,
                               cgcloud__Job_Definition_Template__r.Name,
                               cgcloud__Job_Definition_Template__r.cgcloud__Description__c,
                               cgcloud__Job_Definition_Template__r.cgcloud__Data_Type__c,
                               cgcloud__Mandatory__c
                        FROM cgcloud__Job_Definition_Links__r)
                FROM cgcloud__Job_Definition_List__c
                WHERE cgcloud__Visit_Template__c IN :templateIds
                  AND cgcloud__Active__c = true
                WITH USER_MODE
            ];
            for (cgcloud__Job_Definition_List__c jdl : jdls) {
                if (!templateToJDLs.containsKey(jdl.cgcloud__Visit_Template__c)) {
                    templateToJDLs.put(jdl.cgcloud__Visit_Template__c, new List<cgcloud__Job_Definition_List__c>());
                }
                templateToJDLs.get(jdl.cgcloud__Visit_Template__c).add(jdl);
            }
        }

        // Populate results mapping back to each request
        for (Request req : requests) {
            Result res = new Result();
            res.activities = new List<ActivityInfo>();
            
            if (String.isNotBlank(req.visitId)) {
                Visit v = visitsMap.get(req.visitId);
                if (v != null && v.cgcloud__Visit_Template__c != null && templateToJDLs.containsKey(v.cgcloud__Visit_Template__c)) {
                    for (cgcloud__Job_Definition_List__c jdl : templateToJDLs.get(v.cgcloud__Visit_Template__c)) {
                        ActivityInfo act = new ActivityInfo();
                        act.activityId = jdl.Id;
                        
                        // Use Field Sales Activity details if lookup is populated, else fallback to JDL name
                        if (jdl.cgcloud__Field_Sales_Activity__c != null) {
                            act.activityName = jdl.cgcloud__Field_Sales_Activity__r.Name;
                            act.description = jdl.cgcloud__Field_Sales_Activity__r.cgcloud__Description__c;
                        } else {
                            act.activityName = jdl.Name;
                            act.description = jdl.cgcloud__Description__c;
                        }
                        
                        act.questions = new List<QuestionInfo>();
                        if (jdl.cgcloud__Job_Definition_Links__r != null) {
                            for (cgcloud__Job_DL_Job_Definition_Template__c link : jdl.cgcloud__Job_Definition_Links__r) {
                                QuestionInfo q = new QuestionInfo();
                                q.questionId = link.cgcloud__Job_Definition_Template__c;
                                q.questionName = link.cgcloud__Job_Definition_Template__r.Name;
                                q.description = link.cgcloud__Job_Definition_Template__r.cgcloud__Description__c;
                                q.mandatory = link.cgcloud__Mandatory__c;
                                act.questions.add(q);
                            }
                        }
                        res.activities.add(act);
                    }
                }
            }
            results.add(res);
        }

        return results;
    }
}