force-app/main/default/objects/cgcloud__Job_Definition_List__c/cgcloud__Job_Definition_List__c.object-meta.xml
<CustomObject>
    <description>Holds the set of questions/surveys that are to be carried out in the respective call and contains further relevant configurations.</description>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/fields/cgcloud__Promotion__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>cgcloud__Promotion__c.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Promotion__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Job_Definition_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_List__c/fields/cgcloud__Visit_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Visit_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Visit Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cgcloud__Visit_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>cgcloud__Visit_Template__c.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>$Source.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Visit_Template__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Job_Definition_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/cgcloud__Job_Definition_Template__c.object-meta.xml
<CustomObject>
    <description>Holds the definition of questions / product surveys that are available in the system.</description>
    <label>Job Definition Template</label>
    <nameField>
        <label>Job Definition Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Definition Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/fields/cgcloud__Active__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_Definition_Template__c/fields/cgcloud__Description__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Description__c</fullName>
    <formula>CASE($User.cgcloud__Language_Postfix__c,
      &quot;Language1&quot;, cgcloud__Description_Language_1__c,
      &quot;Language2&quot;, BLANKVALUE(cgcloud__Description_Language_2__c,cgcloud__Description_Language_1__c),
      &quot;Language3&quot;, BLANKVALUE(cgcloud__Description_Language_3__c,cgcloud__Description_Language_1__c),
      &quot;Language4&quot;, BLANKVALUE(cgcloud__Description_Language_4__c,cgcloud__Description_Language_1__c),
      cgcloud__Description_Language_1__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/cgcloud__Job_DL_Job_Definition_Template__c.object-meta.xml
<CustomObject>
    <description>Holds the specific questions/surveys used in the job definition list.</description>
    <label>Question</label>
    <nameField>
        <displayFormat>JDL-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Description__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Description__c</fullName>
    <formula>cgcloud__Job_Definition_Template__r.cgcloud__Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Job_Definition_List__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_List__c</fullName>
    <label>Activity</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Job_Definition_List__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Job_Definition_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cgcloud__Job_DL_Job_Definition_Template__c/fields/cgcloud__Job_Definition_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Definition Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cgcloud__Job_Definition_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>cgcloud__Job_Definition_Template__c.cgcloud__Sales_Org__c</field>
            <operation>equals</operation>
            <valueField>$Source.cgcloud__Sales_Org__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Job_Definition_Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Job_Definition_Links</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Job__c/cgcloud__Visit_Job__c.object-meta.xml
<CustomObject>
    <description>Contains answered questions and product surveys (jobs).</description>
    <label>Visit Job</label>
    <nameField>
        <displayFormat>CJ-{0000}</displayFormat>
        <label>Visit Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cgcloud__Visit_Job__c/fields/cgcloud__Display_Value__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Display_Value__c</fullName>
    <formula>IF(ISPICKVAL(cgcloud__Job_Definition_Template__r.cgcloud__Data_Type__r.cgcloud__Data_Type__c, &quot;Toggle&quot;) ,   cgcloud__Data_Type_Option__r.cgcloud__Description__c   ,  cgcloud__Value__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Answer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Job__c/fields/cgcloud__Done__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Job__c/fields/cgcloud__Job_Definition_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Definition Template</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2) OR (3 AND 4))</booleanFilter>
        <filterItems>
            <field>$Source.cgcloud__Product__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>cgcloud__Job_Definition_Template__c.cgcloud__Job_Template__r.cgcloud__Product_Reference__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.cgcloud__Product__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>cgcloud__Job_Definition_Template__c.cgcloud__Job_Template__r.cgcloud__Product_Reference__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Job_Definition_Template__c</referenceTo>
    <relationshipLabel>Visit Jobs</relationshipLabel>
    <relationshipName>Call_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Job__c/fields/cgcloud__Job_Definition_Template_Description__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Job_Definition_Template_Description__c</fullName>
    <formula>cgcloud__Job_Definition_Template__r.cgcloud__Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Question</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Job__c/fields/cgcloud__Product__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.cgcloud__Product_Template__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Visit Jobs</relationshipLabel>
    <relationshipName>Call_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Job__c/fields/cgcloud__Promotion__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <referenceTo>cgcloud__Promotion__c</referenceTo>
    <relationshipLabel>Visit Jobs</relationshipLabel>
    <relationshipName>Call_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Job__c/fields/cgcloud__Value__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Job__c/fields/cgcloud__Visit__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Visit__c</fullName>
    <label>Visit</label>
    <referenceTo>Visit</referenceTo>
    <relationshipLabel>Visit Jobs</relationshipLabel>
    <relationshipName>Call_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cgcloud__Visit_Template__c/cgcloud__Visit_Template__c.object-meta.xml
<CustomObject>
    <description>Template describing basic call behaviour.</description>
    <label>Visit Template</label>
    <nameField>
        <label>Visit Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit/fields/cgcloud__Visit_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Visit_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Visit Template associated to the Call</description>
    <label>Visit Template</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No matches found or visit Template is not active.</errorMessage>
        <filterItems>
            <field>cgcloud__Visit_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Visit_Template__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

Visit_Activity_Agent_Backup/Visit_Activity_Agent_Backup/force-app/main/default/classes/GetVisitJobsStatus.cls
public with sharing class GetVisitJobsStatus {

    public class Request {
        @InvocableVariable(label='Visit ID' description='The ID of the Visit record' required=true)
        public String visitId;

        @InvocableVariable(label='Status Filter' description='Filter by: all, answered, pending' required=false)
        public String statusFilter;
    }

    public class Result {
        @InvocableVariable(label='Jobs' description='List of matching visit jobs (questions/surveys)')
        public List<JobStatusInfo> jobs;
    }

    public class JobStatusInfo {
        @InvocableVariable(label='Job ID' description='The ID of the Visit Job record')
        public String jobId;

        @InvocableVariable(label='Question Name' description='The Name of the job definition template')
        public String questionName;

        @InvocableVariable(label='Question Description' description='The description of the question/survey')
        public String questionDescription;

        @InvocableVariable(label='Is Done' description='Whether the question/survey has been answered')
        public Boolean isDone;

        @InvocableVariable(label='Value' description='The raw answer value')
        public String value;

        @InvocableVariable(label='Display Value' description='The formatted display answer value')
        public String displayValue;

        @InvocableVariable(label='Product Name' description='Associated product name if applicable')
        public String productName;

        @InvocableVariable(label='Promotion Name' description='Associated promotion name if applicable')
        public String promotionName;
    }

    @InvocableMethod(
        label='Get Visit Jobs Status'
        description='Retrieves answered or pending visit jobs (questions/surveys) for a specific visit, calculating pending from total template questions.'
    )
    public static List<Result> execute(List<Request> requests) {
        List<Result> results = new List<Result>();
        
        Set<Id> visitIds = new Set<Id>();
        for (Request req : requests) {
            if (String.isNotBlank(req.visitId)) {
                visitIds.add((Id)req.visitId);
            }
        }

        if (visitIds.isEmpty()) {
            for (Integer i = 0; i < requests.size(); i++) {
                results.add(new Result());
            }
            return results;
        }

        // Query Visit records to get their template IDs
        Map<Id, Visit> visitsMap = new Map<Id, Visit>([
            SELECT Id, cgcloud__Visit_Template__c
            FROM Visit
            WHERE Id IN :visitIds
            WITH USER_MODE
        ]);

        // Map template IDs to their visits
        Map<Id, Set<Id>> templateToVisits = new Map<Id, Set<Id>>();
        for (Visit v : visitsMap.values()) {
            if (v.cgcloud__Visit_Template__c != null) {
                if (!templateToVisits.containsKey(v.cgcloud__Visit_Template__c)) {
                    templateToVisits.put(v.cgcloud__Visit_Template__c, new Set<Id>());
                }
                templateToVisits.get(v.cgcloud__Visit_Template__c).add(v.Id);
            }
        }

        // Query total planned questions (templates) for these visit templates
        Map<Id, List<cgcloud__Job_DL_Job_Definition_Template__c>> templateToPlannedQuestions = new Map<Id, List<cgcloud__Job_DL_Job_Definition_Template__c>>();
        if (!templateToVisits.isEmpty()) {
            List<cgcloud__Job_DL_Job_Definition_Template__c> plannedList = [
                SELECT cgcloud__Job_Definition_Template__c,
                       cgcloud__Job_Definition_Template__r.Name,
                       cgcloud__Job_Definition_Template__r.cgcloud__Description__c,
                       cgcloud__Job_Definition_List__r.cgcloud__Visit_Template__c
                FROM cgcloud__Job_DL_Job_Definition_Template__c
                WHERE cgcloud__Job_Definition_List__r.cgcloud__Visit_Template__c IN :templateToVisits.keySet()
                  AND cgcloud__Job_Definition_List__r.cgcloud__Active__c = true
                WITH USER_MODE
            ];
            for (cgcloud__Job_DL_Job_Definition_Template__c item : plannedList) {
                Id visitTemplateId = item.cgcloud__Job_Definition_List__r.cgcloud__Visit_Template__c;
                if (!templateToPlannedQuestions.containsKey(visitTemplateId)) {
                    templateToPlannedQuestions.put(visitTemplateId, new List<cgcloud__Job_DL_Job_Definition_Template__c>());
                }
                templateToPlannedQuestions.get(visitTemplateId).add(item);
            }
        }

        // Query all actual Visit Jobs for the collected visits
        List<cgcloud__Visit_Job__c> allVisitJobs = [
            SELECT Id, Name, cgcloud__Visit__c,
                   cgcloud__Job_Definition_Template__c,
                   cgcloud__Job_Definition_Template__r.Name,
                   cgcloud__Job_Definition_Template_Description__c,
                   cgcloud__Done__c,
                   cgcloud__Value__c,
                   cgcloud__Display_Value__c,
                   cgcloud__Product__r.Name,
                   cgcloud__Promotion__r.Name
            FROM cgcloud__Visit_Job__c
            WHERE cgcloud__Visit__c IN :visitIds
            WITH USER_MODE
        ];

        // Map visit jobs by Visit ID
        Map<Id, List<cgcloud__Visit_Job__c>> visitToJobs = new Map<Id, List<cgcloud__Visit_Job__c>>();
        for (cgcloud__Visit_Job__c job : allVisitJobs) {
            if (!visitToJobs.containsKey(job.cgcloud__Visit__c)) {
                visitToJobs.put(job.cgcloud__Visit__c, new List<cgcloud__Visit_Job__c>());
            }
            visitToJobs.get(job.cgcloud__Visit__c).add(job);
        }

        // Process requests
        for (Request req : requests) {
            Result res = new Result();
            res.jobs = new List<JobStatusInfo>();
            
            String filter = String.isNotBlank(req.statusFilter) ? req.statusFilter.toLowerCase() : 'all';
            
            if (String.isNotBlank(req.visitId)) {
                Visit v = visitsMap.get(req.visitId);
                Id visitTemplateId = (v != null) ? v.cgcloud__Visit_Template__c : null;
                
                // Get all actual jobs for this visit
                List<cgcloud__Visit_Job__c> actualJobs = visitToJobs.containsKey(req.visitId) ? visitToJobs.get(req.visitId) : new List<cgcloud__Visit_Job__c>();
                
                // Map to track actual jobs by their Template ID
                Map<Id, List<cgcloud__Visit_Job__c>> templateToActualJobs = new Map<Id, List<cgcloud__Visit_Job__c>>();
                for (cgcloud__Visit_Job__c job : actualJobs) {
                    if (job.cgcloud__Job_Definition_Template__c != null) {
                        if (!templateToActualJobs.containsKey(job.cgcloud__Job_Definition_Template__c)) {
                            templateToActualJobs.put(job.cgcloud__Job_Definition_Template__c, new List<cgcloud__Visit_Job__c>());
                        }
                        templateToActualJobs.get(job.cgcloud__Job_Definition_Template__c).add(job);
                    }
                }
                
                List<JobStatusInfo> answeredJobsList = new List<JobStatusInfo>();
                List<JobStatusInfo> pendingJobsList = new List<JobStatusInfo>();
                
                // Process actual jobs first
                for (cgcloud__Visit_Job__c job : actualJobs) {
                    Boolean isDone = (job.cgcloud__Done__c == true || String.isNotBlank(job.cgcloud__Value__c));
                    
                    JobStatusInfo info = new JobStatusInfo();
                    info.jobId = job.Id;
                    info.questionName = job.cgcloud__Job_Definition_Template__r != null ? job.cgcloud__Job_Definition_Template__r.Name : '';
                    info.questionDescription = job.cgcloud__Job_Definition_Template_Description__c;
                    info.value = job.cgcloud__Value__c;
                    info.displayValue = job.cgcloud__Display_Value__c;
                    info.productName = job.cgcloud__Product__r != null ? job.cgcloud__Product__r.Name : '';
                    info.promotionName = job.cgcloud__Promotion__r != null ? job.cgcloud__Promotion__r.Name : '';
                    
                    if (isDone) {
                        info.isDone = true;
                        answeredJobsList.add(info);
                    } else {
                        info.isDone = false;
                        pendingJobsList.add(info);
                    }
                }
                
                // Process planned templates that have no actual job records
                Set<Id> addedPendingTemplateIds = new Set<Id>();
                if (visitTemplateId != null && templateToPlannedQuestions.containsKey(visitTemplateId)) {
                    for (cgcloud__Job_DL_Job_Definition_Template__c planned : templateToPlannedQuestions.get(visitTemplateId)) {
                        Id tId = planned.cgcloud__Job_Definition_Template__c;
                        // If there are no actual jobs for this template, it is completely pending
                        if (!templateToActualJobs.containsKey(tId) && !addedPendingTemplateIds.contains(tId)) {
                            addedPendingTemplateIds.add(tId);
                            
                            JobStatusInfo info = new JobStatusInfo();
                            info.jobId = '';
                            info.questionName = planned.cgcloud__Job_Definition_Template__r.Name;
                            info.questionDescription = planned.cgcloud__Job_Definition_Template__r.cgcloud__Description__c;
                            info.isDone = false;
                            info.value = '';
                            info.displayValue = '';
                            info.productName = '';
                            info.promotionName = '';
                            pendingJobsList.add(info);
                        }
                    }
                }
                
                // Filter and assemble results
                if (filter == 'answered' || filter == 'completed') {
                    res.jobs.addAll(answeredJobsList);
                } else if (filter == 'pending' || filter == 'unanswered') {
                    res.jobs.addAll(pendingJobsList);
                } else { // 'all'
                    res.jobs.addAll(answeredJobsList);
                    res.jobs.addAll(pendingJobsList);
                }
            }
            results.add(res);
        }

        return results;
    }
}